# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'RickAndMortyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RickAndMortyApp
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.8'
  pod 'Nuke', '~> 10.7'
end
